LGA_TO_AREAS = {
    'Agege': ['Agege Town', 'Dopemu', 'Ifako', 'Oko-Oba', 'Pencinema', 'Orile-Agege', 'Keke'],
    'Ajeromi-Ifelodun': ['Ajegunle', 'Amukoko', 'Layeni', 'Olodi-Apapa', 'Tolu', 'Ifelodun', 'Awodi-Ora'],
    'Alimosho': ['Egbeda', 'Idimu', 'Ipaja', 'Isheri-Oshun', 'Akowonjo', 'Shasha', 'Dopemu', 'Igando', 'Ikotun'],
    'Amuwo-Odofin': ['Festac Town', 'Mile 2', 'Satellite Town', 'Apple Junction', 'Ago Palace Way', 'Kirikiri'],
    'Apapa': ['Apapa Township', 'Ijora', 'Suru-Lere', 'Wharf Road', 'Creek Road', 'Customs Street'],
    'Badagry': ['Badagry Town', 'Ajara', 'Awhanjigo', 'Ibereko', 'Topo', 'Ganyingbo'],
    'Epe': ['Epe Town', 'Agbowa', 'Itoikin', 'Mojoda', 'Poka', 'Ejirin'],
    'Eti-Osa': ['Victoria Island', 'Lekki Phase 1', 'Lekki Phase 2', 'Ajah', 'Ikoyi', 'Oniru', 'Sangotedo', 'Ogombo', 'Abraham Adesanya'],
    'Ibeju-Lekki': ['Ibeju', 'Eleko', 'Akodo', 'Folu Farm', 'Lakowe'],
    'Ifako-Ijaiye': ['Ifako', 'Ijaiye', 'Ojokoro', 'Abule-Egba', 'Iyana-Ipaja', 'Command'],
    'Ikeja': ['Ikeja GRA', 'Allen Avenue', 'Computer Village', 'Alausa', 'Maryland', 'Oregun', 'Toyin Street', 'Obafemi Awolowo Way'],
    'Ikorodu': ['Ikorodu Town', 'Benson', 'Imota', 'Ijede', 'Igbogbo', 'Ipakodo', 'Odogunyan', 'Agric'],
    'Island (Lagos Island)': ['Lagos Island', 'Broad Street', 'Marina', 'Campos', 'Idumota', 'Epetedo', 'Isale-Eko'],
    'Isolo': ['Isolo', 'Mushin', 'Ejigbo', 'Ilasamaja', 'Ago Palace', 'Okota'],
    'Kosofe': ['Ketu', 'Mile 12', 'Ojota', 'Ogudu', 'Ikosi', 'Alapere', 'Magodo'],
    'Lagos Mainland': ['Yaba', 'Ebute-Metta', 'Oyingbo', 'Costain', 'Sabo', 'Herbert Macaulay', 'Palm Grove'],
    'Mushin': ['Mushin Town', 'Idi-Oro', 'Ladipo', 'Ilasamaja', 'Ojuwoye', 'Papa Ajao'],
    'Ojo': ['Ojo Town', 'Ajangbadi', 'Ilogbo', 'Iba', 'Alaba', 'Trade Fair', 'Alaba Rago'],
    'Oshodi-Isolo': ['Oshodi', 'Mafoluku', 'Shogunle', 'Bolade', 'Airport Road', 'Isolo', 'Akowonjo'],
    'Shomolu': ['Shomolu', 'Bariga', 'Gbagada', 'Pedro', 'Onipanu', 'Palmgrove'],
    'Surulere': ['Surulere Town', 'Ojuelegba', 'Aguda', 'Bode Thomas', 'Adeniran Ogunsanya', 'Ijesha', 'Itire', 'Lawanson', 'Eric Moore'],
}

AREA_TO_LGA = {
    'Agege Town': 'Agege',
    'Dopemu': 'Agege',
    'Ifako': 'Agege',
    'Oko-Oba': 'Agege',
    'Pencinema': 'Agege',
    'Orile-Agege': 'Agege',
    'Keke': 'Agege',
    'Ajegunle': 'Ajeromi-Ifelodun',
    'Amukoko': 'Ajeromi-Ifelodun',
    'Layeni': 'Ajeromi-Ifelodun',
    'Olodi-Apapa': 'Ajeromi-Ifelodun',
    'Tolu': 'Ajeromi-Ifelodun',
    'Ifelodun': 'Ajeromi-Ifelodun',
    'Awodi-Ora': 'Ajeromi-Ifelodun',
    'Egbeda': 'Alimosho',
    'Idimu': 'Alimosho',
    'Ipaja': 'Alimosho',
    'Isheri-Oshun': 'Alimosho',
    'Akowonjo': 'Alimosho',
    'Shasha': 'Alimosho',
    'Dopemu': 'Alimosho',
    'Igando': 'Alimosho',
    'Ikotun': 'Alimosho',
    'Festac Town': 'Amuwo-Odofin',
    'Mile 2': 'Amuwo-Odofin',
    'Satellite Town': 'Amuwo-Odofin',
    'Apple Junction': 'Amuwo-Odofin',
    'Ago Palace Way': 'Amuwo-Odofin',
    'Kirikiri': 'Amuwo-Odofin',
    'Apapa Township': 'Apapa',
    'Ijora': 'Apapa',
    'Suru-Lere': 'Apapa',
    'Wharf Road': 'Apapa',
    'Creek Road': 'Apapa',
    'Customs Street': 'Apapa',
    'Badagry Town': 'Badagry',
    'Ajara': 'Badagry',
    'Awhanjigo': 'Badagry',
    'Ibereko': 'Badagry',
    'Topo': 'Badagry',
    'Ganyingbo': 'Badagry',
    'Epe Town': 'Epe',
    'Agbowa': 'Epe',
    'Itoikin': 'Epe',
    'Mojoda': 'Epe',
    'Poka': 'Epe',
    'Ejirin': 'Epe',
    'Victoria Island': 'Eti-Osa',
    'Lekki Phase 1': 'Eti-Osa',
    'Lekki Phase 2': 'Eti-Osa',
    'Ajah': 'Eti-Osa',
    'Ikoyi': 'Eti-Osa',
    'Oniru': 'Eti-Osa',
    'Sangotedo': 'Eti-Osa',
    'Ogombo': 'Eti-Osa',
    'Abraham Adesanya': 'Eti-Osa',
    'Ibeju': 'Ibeju-Lekki',
    'Eleko': 'Ibeju-Lekki',
    'Akodo': 'Ibeju-Lekki',
    'Folu Farm': 'Ibeju-Lekki',
    'Lakowe': 'Ibeju-Lekki',
    'Ifako': 'Ifako-Ijaiye',
    'Ijaiye': 'Ifako-Ijaiye',
    'Ojokoro': 'Ifako-Ijaiye',
    'Abule-Egba': 'Ifako-Ijaiye',
    'Iyana-Ipaja': 'Ifako-Ijaiye',
    'Command': 'Ifako-Ijaiye',
    'Ikeja GRA': 'Ikeja',
    'Allen Avenue': 'Ikeja',
    'Computer Village': 'Ikeja',
    'Alausa': 'Ikeja',
    'Maryland': 'Ikeja',
    'Oregun': 'Ikeja',
    'Toyin Street': 'Ikeja',
    'Obafemi Awolowo Way': 'Ikeja',
    'Ikorodu Town': 'Ikorodu',
    'Benson': 'Ikorodu',
    'Imota': 'Ikorodu',
    'Ijede': 'Ikorodu',
    'Igbogbo': 'Ikorodu',
    'Ipakodo': 'Ikorodu',
    'Odogunyan': 'Ikorodu',
    'Agric': 'Ikorodu',
    'Lagos Island': 'Island (Lagos Island)',
    'Broad Street': 'Island (Lagos Island)',
    'Marina': 'Island (Lagos Island)',
    'Campos': 'Island (Lagos Island)',
    'Idumota': 'Island (Lagos Island)',
    'Epetedo': 'Island (Lagos Island)',
    'Isale-Eko': 'Island (Lagos Island)',
    'Isolo': 'Isolo',
    'Mushin': 'Isolo',
    'Ejigbo': 'Isolo',
    'Ilasamaja': 'Isolo',
    'Ago Palace': 'Isolo',
    'Okota': 'Isolo',
    'Ketu': 'Kosofe',
    'Mile 12': 'Kosofe',
    'Ojota': 'Kosofe',
    'Ogudu': 'Kosofe',
    'Ikosi': 'Kosofe',
    'Alapere': 'Kosofe',
    'Magodo': 'Kosofe',
    'Yaba': 'Lagos Mainland',
    'Ebute-Metta': 'Lagos Mainland',
    'Oyingbo': 'Lagos Mainland',
    'Costain': 'Lagos Mainland',
    'Sabo': 'Lagos Mainland',
    'Herbert Macaulay': 'Lagos Mainland',
    'Palm Grove': 'Lagos Mainland',
    'Mushin Town': 'Mushin',
    'Idi-Oro': 'Mushin',
    'Ladipo': 'Mushin',
    'Ilasamaja': 'Mushin',
    'Ojuwoye': 'Mushin',
    'Papa Ajao': 'Mushin',
    'Ojo Town': 'Ojo',
    'Ajangbadi': 'Ojo',
    'Ilogbo': 'Ojo',
    'Iba': 'Ojo',
    'Alaba': 'Ojo',
    'Trade Fair': 'Ojo',
    'Alaba Rago': 'Ojo',
    'Oshodi': 'Oshodi-Isolo',
    'Mafoluku': 'Oshodi-Isolo',
    'Shogunle': 'Oshodi-Isolo',
    'Bolade': 'Oshodi-Isolo',
    'Airport Road': 'Oshodi-Isolo',
    'Isolo': 'Oshodi-Isolo',
    'Akowonjo': 'Oshodi-Isolo',
    'Shomolu': 'Shomolu',
    'Bariga': 'Shomolu',
    'Gbagada': 'Shomolu',
    'Pedro': 'Shomolu',
    'Onipanu': 'Shomolu',
    'Palmgrove': 'Shomolu',
    'Surulere Town': 'Surulere',
    'Ojuelegba': 'Surulere',
    'Aguda': 'Surulere',
    'Bode Thomas': 'Surulere',
    'Adeniran Ogunsanya': 'Surulere',
    'Ijesha': 'Surulere',
    'Itire': 'Surulere',
    'Lawanson': 'Surulere',
    'Eric Moore': 'Surulere',
}

def normalize_scope_value(value):
    return str(value or "").strip().lower()

def areas_for_lga(lga):
    if not lga:
        return []
    target = normalize_scope_value(lga)
    for key, areas in LGA_TO_AREAS.items():
        if normalize_scope_value(key) == target:
            return areas
    return []

def resolve_lga(*, lga="", area="", service_area=""):
    if lga:
        return str(lga).strip()
    for candidate in [area, service_area]:
        key = str(candidate or "").strip()
        if key in AREA_TO_LGA:
            return AREA_TO_LGA[key]
    return ""

def service_area_matches_lga(service_area, lga):
    if not service_area or not lga:
        return False
    normalized_service_area = normalize_scope_value(service_area)
    normalized_lga = normalize_scope_value(lga)
    if normalized_service_area == normalized_lga:
        return True
    return any(normalize_scope_value(area) == normalized_service_area for area in areas_for_lga(lga))
