# Generated by Django 6.0.4 on 2026-06-17 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='lga',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Request Created'), ('REVIEWED', 'Request Reviewed'), ('ASSIGNED', 'Collector Assigned'), ('ACCEPTED', 'Collector Accepted'), ('ON_THE_WAY', 'Collector En Route'), ('COMPLETED', 'Completed'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('FAILED', 'Failed')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pickups.pickuprequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
