# Generated by Django 6.0.4 on 2026-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], default='SMS', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('REQUEST_RECEIVED', 'Request Received'), ('JOB_ASSIGNED', 'Job Assigned'), ('COLLECTOR_ACCEPTED', 'Collector Accepted'), ('COLLECTOR_ON_THE_WAY', 'Collector On The Way'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_MISSED', 'Job Missed')], default='SMS', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
